port module Main exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)


port ready : () -> Cmd msg


type alias Model =
    String


type Msg
    = NoOp


init : ( Model, Cmd Msg )
init =
    ( "", ready () )


view : Model -> Html Msg
view model =
    section [ id "main" ]
        [ header []
            [ div [ id "header-image" ]
                [ img [ src "resources/img/logo.svg" ]
                    []
                ]
            , div [ id "header-name" ]
                [ text "PATHFINDER" ]
            ]
        , nav [ id "primary" ]
            [ div [ class "menu active", id "primary-top" ]
                [ text "TOP" ]
            , div [ class "menu", id "primary-aboutme" ]
                [ text "ABOUT ME" ]
            , div [ class "menu", id "primary-articles" ]
                [ text "ARTICLES" ]
            , div [ class "menu", id "primary-products" ]
                [ text "PRODUCTS" ]
            , div [ class "menu", id "primary-experiences" ]
                [ text "EXPERIENCES" ]
            , div [ class "menu", id "primary-archives" ]
                [ text "ARCHIVES" ]
            , div [ class "menu", id "primary-credit" ]
                [ text "CREDIT" ]
            ]
        , section [ id "pages" ]
            [ article [ class "page", id "pages-top" ]
                [ div [ class "main" ]
                    [ div [ class "line", id "pages-top-top-left" ]
                        [ div [ class "vertical" ]
                            []
                        , div [ class "horizontal" ]
                            []
                        ]
                    , div [ class "line", id "pages-top-bottom-left" ]
                        [ div [ class "vertical" ]
                            []
                        , div [ class "horizontal" ]
                            []
                        ]
                    , div [ class "line", id "pages-top-top-right" ]
                        [ div [ class "vertical" ]
                            []
                        , div [ class "horizontal" ]
                            []
                        ]
                    , div [ class "line", id "pages-top-bottom-right" ]
                        [ div [ class "vertical" ]
                            []
                        , div [ class "horizontal" ]
                            []
                        ]
                    , div [ id "pages-top-logo" ]
                        [ div [ id "pages-top-logo-image" ]
                            [ img [ src "resources/img/logo.svg" ]
                                []
                            ]
                        , div [ id "pages-top-logo-name" ]
                            [ text "PATHFINDER" ]
                        ]
                    , div [ id "pages-top-urge-scroll" ]
                        [ text "SCROLL              "
                        , div [ id "pages-top-urge-scroll-image" ]
                            [ img [ src "resources/img/down.svg" ]
                                []
                            ]
                        ]
                    ]
                ]
            , article [ class "page", id "pages-aboutme" ]
                [ div [ class "main" ]
                    [ div [ id "pages-aboutme-container" ]
                        [ div [ id "pages-aboutme-name" ]
                            [ text "Marei Kikukawa" ]
                        , div [ id "pages-aboutme-screenname" ]
                            [ text "Calmery" ]
                        , div [ class "label" ]
                            [ text "Location" ]
                        , div [ class "text" ]
                            [ text "Fukuoka, Japan" ]
                        , div [ class "label" ]
                            [ text "Organization" ]
                        , div [ class "text" ]
                            [ text "Sojo University" ]
                        , div [ class "text" ]
                            [ text "Department of Computer and Information Sciences" ]
                        , div [ class "label" ]
                            [ text "Programming Languages" ]
                        , div [ class "text" ]
                            [ text "JavaScript" ]
                        , div [ class "text" ]
                            [ text "Elm" ]
                        , div [ class "label" ]
                            [ text "Interests" ]
                        , div [ class "text" ]
                            [ text "Functional Programming Language" ]
                        , div [ class "text" ]
                            [ text "Concurrent Programming" ]
                        , div [ class "text" ]
                            [ text "Web Real-Time Communication" ]
                        ]
                    ]
                ]
            , article [ class "page", id "pages-articles" ]
                [ div [ class "main" ]
                    [ div [ id "pages-articles-container" ]
                        [ div [ id "pages-articles-title" ]
                            [ text "QIITA" ]
                        , div [ id "pages-articles-description" ]
                            [ text "THERE ARE 2 ARTICLES ON HATENA BLOG" ]
                        , div [ id "pages-articles-articles" ]
                            [ div [ class "article" ]
                                [ div [ class "title" ]
                                    [ span [ class "p" ]
                                        [ text "Hyperapp" ]
                                    , text "を読む"
                                    ]
                                , div [ class "body" ]
                                    [ text "読んだのでまとめる．"
                                    , span [ class "p" ]
                                        [ text "Hyperapp" ]
                                    , text "とは "
                                    , span [ class "p" ]
                                        [ text "2018" ]
                                    , text "年は "
                                    , span [ class "p" ]
                                        [ text "Hyperapp" ]
                                    , text "の年だ を読むとわかる．読んでみる 読みやすさのために少し書き換えている．"
                                    , span [ class "p" ]
                                        [ text "h" ]
                                    , text "関数 "
                                    , span [ class "p" ]
                                        [ text "h" ]
                                    , text "関数は与えられた引数から "
                                    , span [ class "p" ]
                                        [ text "Hyperapp" ]
                                    , text "の仮想 "
                                    , span [ class "p" ]
                                        [ text "DOM" ]
                                    , text "…"
                                    ]
                                , div [ class "date" ]
                                    [ text "Dec. 31, 2017" ]
                                , div [ class "continue" ]
                                    [ text "続きを読む" ]
                                ]
                            , div [ class "article" ]
                                [ div [ class "title" ]
                                    [ span [ class "p" ]
                                        [ text "Hyperapp" ]
                                    , text "を読む"
                                    ]
                                , div [ class "body" ]
                                    [ text "読んだのでまとめる．"
                                    , span [ class "p" ]
                                        [ text "Hyperapp" ]
                                    , text "とは "
                                    , span [ class "p" ]
                                        [ text "2018" ]
                                    , text "年は "
                                    , span [ class "p" ]
                                        [ text "Hyperapp" ]
                                    , text "の年だ を読むとわかる．読んでみる 読みやすさのために少し書き換えている．"
                                    , span [ class "p" ]
                                        [ text "h" ]
                                    , text "関数 "
                                    , span [ class "p" ]
                                        [ text "h" ]
                                    , text "関数は与えられた引数から "
                                    , span [ class "p" ]
                                        [ text "Hyperapp" ]
                                    , text "の仮想 "
                                    , span [ class "p" ]
                                        [ text "DOM" ]
                                    , text "…"
                                    ]
                                , div [ class "date" ]
                                    [ text "Dec. 31, 2017" ]
                                , div [ class "continue" ]
                                    [ text "続きを読む" ]
                                ]
                            , div [ class "article" ]
                                [ div [ class "more" ]
                                    [ img [ src "resources/img/href.svg" ]
                                        []
                                    , div [ class "text" ]
                                        [ text "READ MORE" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            , article [ class "page", id "pages-products" ]
                [ div [ class "main" ]
                    [ div [ class "information" ]
                        [ div [ class "name" ]
                            [ text "PATHFINDER" ]
                        , div [ class "date" ]
                            [ text "2018" ]
                        ]
                    , div [ class "mockup" ]
                        [ div [ class "pc" ]
                            [ div [ class "header" ]
                                [ div [ class "buttons" ]
                                    [ div [ class "button red" ]
                                        []
                                    , div [ class "button yellow" ]
                                        []
                                    , div [ class "button green" ]
                                        []
                                    ]
                                ]
                            , div [ class "screen" ]
                                [ div []
                                    [ text "NO IMAGE AVAILABLE" ]
                                , img [ src "" ]
                                    []
                                ]
                            ]
                        , div [ class "sp" ]
                            [ div [ class "statusbar" ]
                                [ img [ class "icon-4g", src "resources/img/4g.svg" ]
                                    []
                                , img [ class "icon-wifi", src "resources/img/wifi.svg" ]
                                    []
                                , img [ class "icon-battery", src "resources/img/battery.svg" ]
                                    []
                                ]
                            , div [ class "screen" ]
                                [ div []
                                    [ text "NO IMAGE"
                                    , br []
                                        []
                                    , text "AVAILABLE"
                                    ]
                                , img [ src "" ]
                                    []
                                ]
                            ]
                        ]
                    , div [ class "description" ]
                        [ span [ class "p" ]
                            [ text "Elm" ]
                        , text "を使用して開発しました．"
                        ]
                    , div [ class "repository" ]
                        [ div []
                            [ text "calmery/calmery.me" ]
                        , div [ class "url" ]
                            [ text "https://github.com/calmery/calmery.me" ]
                        ]
                    ]
                ]
            , article [ class "page", id "pages-experiences" ]
                [ div [ class "main" ]
                    [ div [ id "pages-experiences-line" ]
                        []
                    , div [ id "pages-experiences-line-bottom" ]
                        []
                    , div [ id "pages-experiences-contents" ]
                        [ div [ class "content" ]
                            [ div [ class "left" ]
                                [ div []
                                    [ text "ソロプチミスト日本財団" ]
                                , div [ class "date" ]
                                    [ text "Nov. 17, 2017" ]
                                ]
                            , div [ class "middle" ]
                                [ div [ class "circle" ]
                                    [ div [ class "inner-circle" ]
                                        []
                                    ]
                                ]
                            , div [ class "right" ]
                                [ div []
                                    [ text "学生ボランティア賞" ]
                                , div [ class "description" ]
                                    [ text "サイバーボランティアで開発したアプリケーションとその活動内容について表彰を受けた．" ]
                                , div [ class "url" ]
                                    [ text "http://www.soro-jpf.net/project/assist_list/" ]
                                ]
                            ]
                        , div [ class "content" ]
                            [ div [ class "left" ]
                                [ div []
                                    [ text "ソロプチミスト日本財団" ]
                                , div [ class "date" ]
                                    [ text "Nov. 17, 2017" ]
                                ]
                            , div [ class "middle" ]
                                [ div [ class "circle" ]
                                    [ div [ class "inner-circle" ]
                                        []
                                    ]
                                ]
                            , div [ class "right" ]
                                [ div []
                                    [ text "学生ボランティア賞" ]
                                , div [ class "description" ]
                                    [ text "サイバーボランティアで開発したアプリケーションとその活動内容について表彰を受けた．" ]
                                , div [ class "url" ]
                                    [ text "http://www.soro-jpf.net/project/assist_list/" ]
                                ]
                            ]
                        , div [ class "content" ]
                            [ div [ class "left" ]
                                [ div []
                                    [ text "ソロプチミスト日本財団" ]
                                , div [ class "date" ]
                                    [ text "Nov. 17, 2017" ]
                                ]
                            , div [ class "middle" ]
                                [ div [ class "circle" ]
                                    [ div [ class "inner-circle" ]
                                        []
                                    ]
                                ]
                            , div [ class "right" ]
                                [ div []
                                    [ text "学生ボランティア賞" ]
                                , div [ class "description" ]
                                    [ text "サイバーボランティアで開発したアプリケーションとその活動内容について表彰を受けた．" ]
                                , div [ class "url" ]
                                    [ text "http://www.soro-jpf.net/project/assist_list/" ]
                                ]
                            ]
                        , div [ class "content" ]
                            [ div [ class "left" ]
                                [ div []
                                    [ text "ソロプチミスト日本財団" ]
                                , div [ class "date" ]
                                    [ text "Nov. 17, 2017" ]
                                ]
                            , div [ class "middle" ]
                                [ div [ class "circle" ]
                                    [ div [ class "inner-circle" ]
                                        []
                                    ]
                                ]
                            , div [ class "right" ]
                                [ div []
                                    [ text "学生ボランティア賞" ]
                                , div [ class "description" ]
                                    [ text "サイバーボランティアで開発したアプリケーションとその活動内容について表彰を受けた．" ]
                                , div [ class "url" ]
                                    [ text "http://www.soro-jpf.net/project/assist_list/" ]
                                ]
                            ]
                        , div [ class "content" ]
                            [ div [ class "left" ]
                                [ div []
                                    [ text "ソロプチミスト日本財団" ]
                                , div [ class "date" ]
                                    [ text "Nov. 17, 2017" ]
                                ]
                            , div [ class "middle" ]
                                [ div [ class "circle" ]
                                    [ div [ class "inner-circle" ]
                                        []
                                    ]
                                ]
                            , div [ class "right" ]
                                [ div []
                                    [ text "学生ボランティア賞" ]
                                , div [ class "description" ]
                                    [ text "サイバーボランティアで開発したアプリケーションとその活動内容について表彰を受けた．" ]
                                , div [ class "url" ]
                                    [ text "http://www.soro-jpf.net/project/assist_list/" ]
                                ]
                            ]
                        ]
                    ]
                ]
            , article [ class "page", id "pages-archives" ]
                [ div [ class "main" ]
                    [ div [ id "pages-archives-title" ]
                        [ text "ARCHIVES" ]
                    , div [ id "pages-archives-container" ]
                        [ div [ class "left" ]
                            [ div [ class "content" ]
                                [ div []
                                    [ text "熊本地震で漏水・給水情報を伝えた"
                                    , span [ class "p" ]
                                        [ text "mizuderu.info" ]
                                    , text "開発の舞台裏"
                                    ]
                                , div [ class "url" ]
                                    [ text "http://ascii.jp/elem/000/001/252/1252559/" ]
                                ]
                            ]
                        , div [ class "right" ]
                            [ div [ class "content" ]
                                [ div []
                                    [ text "熊本地震で漏水・給水情報を伝えた"
                                    , span [ class "p" ]
                                        [ text "mizuderu.info" ]
                                    , text "開発の舞台裏"
                                    ]
                                , div [ class "url" ]
                                    [ text "http://ascii.jp/elem/000/001/252/1252559/" ]
                                ]
                            , div [ class "content" ]
                                [ div []
                                    [ text "熊本地震で漏水・給水情報を伝えた"
                                    , span [ class "p" ]
                                        [ text "mizuderu.info" ]
                                    , text "開発の舞台裏"
                                    ]
                                , div [ class "url" ]
                                    [ text "http://ascii.jp/elem/000/001/252/1252559/" ]
                                ]
                            ]
                        ]
                    ]
                ]
            , article [ class "page", id "pages-credit" ]
                [ div [ class "main" ]
                    [ div [ id "pages-credit-title" ]
                        [ text "CREDIT" ]
                    , div [ id "pages-credit-container" ]
                        [ div [ class "left" ]
                            [ div [ class "content" ]
                                [ div []
                                    [ span [ class "p" ]
                                        [ text "iOS 8 Status Bars Sketch Resource by Aubrey Johnson" ]
                                    ]
                                , div [ class "url" ]
                                    [ text "https://www.sketchappsources.com/free-source/1112-ios8-status-bar-sketch-freebie-resource.html" ]
                                ]
                            ]
                        , div [ class "right" ]
                            [ div [ class "content" ]
                                [ div []
                                    [ span [ class "p" ]
                                        [ text "iOS 8 Status Bars Sketch Resource by Aubrey Johnson" ]
                                    ]
                                , div [ class "url" ]
                                    [ text "https://www.sketchappsources.com/free-source/1112-ios8-status-bar-sketch-freebie-resource.html" ]
                                ]
                            , div [ class "content" ]
                                [ div []
                                    [ span [ class "p" ]
                                        [ text "iOS 8 Status Bars Sketch Resource by Aubrey Johnson" ]
                                    ]
                                , div [ class "url" ]
                                    [ text "https://www.sketchappsources.com/free-source/1112-ios8-status-bar-sketch-freebie-resource.html" ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        , nav [ id "secondary" ]
            [ div [ id "secondary-label" ]
                [ text "CONTENTS" ]
            , div [ id "secondary-border" ]
                [ div []
                    []
                ]
            , div [ class "menu active" ]
                [ div [ class "circle" ]
                    []
                , div [ class "name" ]
                    [ text "NAME" ]
                ]
            , div [ class "menu" ]
                [ div [ class "circle" ]
                    []
                , div [ class "name" ]
                    [ text "NAME" ]
                ]
            ]
        , footer []
            [ div [ class "link" ]
                [ a [ href "https://facebook.com/marei.kikukawa" ]
                    [ img [ src "resources/img/facebook.svg" ]
                        []
                    ]
                ]
            , div [ class "link" ]
                [ a [ href "https://twitter.com/calmeryme" ]
                    [ img [ src "resources/img/twitter.svg" ]
                        []
                    ]
                ]
            , div [ class "link" ]
                [ a [ href "https://github.com/calmery" ]
                    [ img [ src "resources/img/github.svg" ]
                        []
                    ]
                ]
            , div [ class "link" ]
                [ a [ href "https://qiita.com/calmery" ]
                    [ img [ src "resources/img/qiita.svg" ]
                        []
                    ]
                ]
            , div [ class "link" ]
                [ a [ href "http://calmery.hatenablog.com" ]
                    [ img [ src "resources/img/blog.svg" ]
                        []
                    ]
                ]
            ]
        ]


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    ( model, Cmd.none )


subscriptions : Model -> Sub Msg
subscriptions model =
    Sub.none


main : Program Never Model Msg
main =
    program
        { init = init
        , view = view
        , update = update
        , subscriptions = subscriptions
        }
